CXX := g++
CXXFLAGS := -std=c++20 -Wall -Wextra -pedantic
LDFLAGS := -lsfml-graphics -lsfml-window -lsfml-system

main: main.cpp
	$(CXX) $(CXXFLAGS) main.cpp -o main.out $(LDFLAGS)

clear:
	rm -f *.out